
# Basic workflow to test website availability with cURL

name: Test Website Availability with cURL

on: 
    push:

jobs:
    curl-test:
        runs-on: ubuntu-latest
        if: ${{ contains(github.event.head_commit.message, '[test]') }}
        steps: 
            - name: Test Page Availability
              run: |
                STATUS=$(curl -s -o /dev/null -w "%{http_code}" -f "https://brendans-website.vercel.app/" || echo "000")
                echo "HTTP Status: $STATUS"
                if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 400 ]; then
                    echo "Website is available"
                else
                    echo "Website check failed"
                    exit 1
                fi