
# Deployment workflow

name: Deploy Website to Vercel

on: 
    push: 
        branches: 
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        if: contains(github.event.head_commit.message, '[deploy]')
        steps: 
            - name: Deploy to Vercel
              run: |
                curl -X POST ${{ secrets.VERCEL_DEPLOY_HK }}



