
# 

name: Site Health Test Workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:


jobs:
    health-test:
        if: contains(github.event.head_commit.message, '[test]')
        runs-on: ubuntu-latest

        steps:
            - name: Site Health Test
              run: |
                STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" https://brendans-website.vercel.app/)
                echo "Status code: $STATUS_CODE"
                if [ "$STATUS_CODE" -ne 200 ]; then
                    echo "Site is down or unhealthy!"
                    exit 1
                else
                    echo "Site is healthy."
                fi
