

name: Website Health Check

# Run daily at 5PM or manually
on:
    schedule:
        - cron: "0 17 * * *"
    workflow_dispatch:


jobs:
    site-health:
        runs-on: ubuntu-latest

        steps: 
            - name: Test Page Availability
              run: |
                STATUS=$(curl -s -o /dev/null -w "%{http_code}" -f "https://brendans-website.vercel.app/" || echo "000")
                echo "HTTP Status: $STATUS"
                if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 400 ]; then
                    echo "Website is available"
                else
                    echo "Website check failed"
                    exit 1
                fi
            
            - name: Verify Homepage Content
              run: |
                RESPONSE=$(curl -s "https://brendans-website.vercel.app/")
                if echo "$RESPONSE" | grep -q "<title>Brendans Website Portfolio</title>"; then
                    echo "Homepage content contains expected content"
                else
                    echo "Homepage content verification failed"
                    exit 1
                fi
            
            - name: Verify About, Projects, Contact Pages
              run: |
                for PAGE in "about" "projects" "contact"; do
                    RESPONSE=$(curl -s "https://brendans-website.vercel.app/$PAGE")
                    if echo "$RESPONSE" | grep -q "<h1>"; then
                        echo "$PAGE page content contains expected content"
                    else
                        echo "$PAGE page content verification failed"
                        exit 1
                    fi
                done