
# Actions Workflow to monitor the health of my portfolio website

name: Website Health Check

# Run daily at 5PM or manually
on:
    schedule:
        - cron: "0 17 * * *"
    workflow_dispatch:


jobs:
    site-health:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Test Page Availability
              run: |
                STATUS=$(curl -s -o /dev/null -w "%{http_code}" -f "https://brendans-website.vercel.app/" || echo "000")
                echo "HTTP Status: $STATUS"
                if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 400 ]; then
                    echo "Website is available"
                else
                    echo "Website check failed"
                    exit 1
                fi
            
            - name: Verify Homepage Content
              run: |
                RESPONSE=$(curl -s "https://brendans-website.vercel.app/")
                if echo "$RESPONSE" | grep -q "<title>Brendans Website Portfolio</title>"; then
                    echo "Homepage content contains expected content"
                else
                    echo "Homepage content verification failed"
                    exit 1
                fi
            
            - name: Cache Node Modules
              uses: actions/cache@v3
              with:
                path: frontend/node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-modules-
            
            - name: Cache Playwright Browsers
              uses: actions/cache@v3
              with:
                path: ~/.cache/ms-playwright
                key: ${{ runner.os }}-playwright-${{ hashFiles('frontend/package-lock.json') }}
            
            - name: Run Playwright Tests
              working-directory: ./frontend
              run: |
                npm install
                npx playwright install --with-deps
                npx playwright test --headless --reporter=dot